[package]
name = "pyratatui"
version = "0.3.0"
edition = "2024"
rust-version = "1.88"
description = "Python bindings for Ratatui"
license = "MIT"
repository = "https://github.com/pyratatui/pyratatui"
keywords = ["ratatui", "tui", "terminal", "bindings"]
categories = ["api-bindings"]

[lib]
name = "pyratatui"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["abi3-py310"] }
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm_0_29", "widget-calendar"] }
crossterm = "0.29"
time = "0.3"

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1
