"""Type stubs for the pyratatui native extension module."""

from collections.abc import Callable

__version__: str
__ratatui_version__: str

__all__: list[str]

class PyratatuiError(Exception): ...
class BackendError(PyratatuiError): ...
class LayoutError(PyratatuiError): ...
class RenderError(PyratatuiError): ...
class AsyncError(PyratatuiError): ...
class StyleError(PyratatuiError): ...

class Color:
    def __init__(self) -> None: ...
    @staticmethod
    def reset() -> Color: ...
    @staticmethod
    def black() -> Color: ...
    @staticmethod
    def red() -> Color: ...
    @staticmethod
    def green() -> Color: ...
    @staticmethod
    def yellow() -> Color: ...
    @staticmethod
    def blue() -> Color: ...
    @staticmethod
    def magenta() -> Color: ...
    @staticmethod
    def cyan() -> Color: ...
    @staticmethod
    def gray() -> Color: ...
    @staticmethod
    def dark_gray() -> Color: ...
    @staticmethod
    def light_red() -> Color: ...
    @staticmethod
    def light_green() -> Color: ...
    @staticmethod
    def light_yellow() -> Color: ...
    @staticmethod
    def light_blue() -> Color: ...
    @staticmethod
    def light_magenta() -> Color: ...
    @staticmethod
    def light_cyan() -> Color: ...
    @staticmethod
    def white() -> Color: ...
    @staticmethod
    def indexed(index: int) -> Color: ...
    @staticmethod
    def rgb(r: int, g: int, b: int) -> Color: ...

class Modifier:
    def __init__(self) -> None: ...
    @staticmethod
    def bold() -> Modifier: ...
    @staticmethod
    def dim() -> Modifier: ...
    @staticmethod
    def italic() -> Modifier: ...
    @staticmethod
    def underlined() -> Modifier: ...
    @staticmethod
    def slow_blink() -> Modifier: ...
    @staticmethod
    def rapid_blink() -> Modifier: ...
    @staticmethod
    def reversed() -> Modifier: ...
    @staticmethod
    def hidden() -> Modifier: ...
    @staticmethod
    def crossed_out() -> Modifier: ...
    def __or__(self, other: Modifier) -> Modifier: ...
    def __and__(self, other: Modifier) -> Modifier: ...

class Style:
    def __init__(self) -> None: ...
    def fg(self, color: Color) -> Style: ...
    def bg(self, color: Color) -> Style: ...
    def add_modifier(self, modifier: Modifier) -> Style: ...
    def remove_modifier(self, modifier: Modifier) -> Style: ...
    def patch(self, other: Style) -> Style: ...
    def bold(self) -> Style: ...
    def italic(self) -> Style: ...
    def underlined(self) -> Style: ...
    def dim(self) -> Style: ...
    def reversed(self) -> Style: ...
    def hidden(self) -> Style: ...
    def crossed_out(self) -> Style: ...
    def slow_blink(self) -> Style: ...
    def rapid_blink(self) -> Style: ...
    @property
    def foreground(self) -> Color | None: ...
    @property
    def background(self) -> Color | None: ...

class Span:
    def __init__(self, content: str, style: Style | None = ...) -> None: ...
    @property
    def content(self) -> str: ...
    @property
    def style(self) -> Style | None: ...
    def styled(self, style: Style) -> Span: ...
    def width(self) -> int: ...

class Line:
    def __init__(self, spans: list[Span] | None = ..., style: Style | None = ...) -> None: ...
    @staticmethod
    def from_string(s: str) -> Line: ...
    def left_aligned(self) -> Line: ...
    def centered(self) -> Line: ...
    def right_aligned(self) -> Line: ...
    def styled(self, style: Style) -> Line: ...
    def push_span(self, span: Span) -> None: ...
    @property
    def spans(self) -> list[Span]: ...
    def width(self) -> int: ...

class Text:
    def __init__(self, lines: list[Line] | None = ..., style: Style | None = ...) -> None: ...
    @staticmethod
    def from_string(s: str) -> Text: ...
    def push_line(self, line: Line) -> None: ...
    def push_str(self, s: str) -> None: ...
    @property
    def height(self) -> int: ...
    def width(self) -> int: ...
    def centered(self) -> Text: ...
    def right_aligned(self) -> Text: ...
    def styled(self, style: Style) -> Text: ...
    @property
    def lines(self) -> list[Line]: ...

class Rect:
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def bottom(self) -> int: ...
    @property
    def left(self) -> int: ...
    @property
    def top(self) -> int: ...
    def area(self) -> int: ...
    def is_empty(self) -> bool: ...
    def inner(self, horizontal: int = ..., vertical: int = ...) -> Rect: ...
    def contains(self, other: Rect) -> bool: ...
    def intersection(self, other: Rect) -> Rect | None: ...
    def union(self, other: Rect) -> Rect: ...

class Constraint:
    @staticmethod
    def length(n: int) -> Constraint: ...
    @staticmethod
    def percentage(pct: int) -> Constraint: ...
    @staticmethod
    def fill(n: int) -> Constraint: ...
    @staticmethod
    def min(n: int) -> Constraint: ...
    @staticmethod
    def max(n: int) -> Constraint: ...
    @staticmethod
    def ratio(num: int, den: int) -> Constraint: ...

class Direction:
    Horizontal: Direction
    Vertical: Direction

class Alignment:
    Left: Alignment
    Center: Alignment
    Right: Alignment

class Layout:
    def __init__(self) -> None: ...
    def constraints(self, constraints: list[Constraint]) -> Layout: ...
    def direction(self, direction: Direction) -> Layout: ...
    def margin(self, margin: int) -> Layout: ...
    def spacing(self, spacing: int) -> Layout: ...
    def flex_mode(self, mode: str) -> Layout: ...
    def split(self, area: Rect) -> list[Rect]: ...

class Buffer:
    def __init__(self, area: Rect) -> None: ...
    @property
    def area(self) -> Rect: ...
    def set_string(self, x: int, y: int, text: str, style: Style | None = ...) -> None: ...
    def set_span(self, x: int, y: int, span: Span) -> None: ...
    def get_string(self, x: int, y: int, width: int) -> str: ...
    def reset(self) -> None: ...
    def merge(self, other: Buffer) -> None: ...

class BorderType:
    Plain: BorderType
    Rounded: BorderType
    Double: BorderType
    Thick: BorderType
    QuadrantInside: BorderType
    QuadrantOutside: BorderType
    LightDoubleDashed: BorderType
    HeavyDoubleDashed: BorderType
    LightTripleDashed: BorderType
    HeavyTripleDashed: BorderType
    LightQuadrupleDashed: BorderType
    HeavyQuadrupleDashed: BorderType

class Block:
    def __init__(self) -> None: ...
    def title(self, title: str) -> Block: ...
    def title_bottom(self, title: str) -> Block: ...
    def bordered(self) -> Block: ...
    def borders(
        self, top: bool = ..., right: bool = ..., bottom: bool = ..., left: bool = ...
    ) -> Block: ...
    def border_type(self, bt: BorderType) -> Block: ...
    def style(self, style: Style) -> Block: ...
    def title_style(self, style: Style) -> Block: ...
    def border_style(self, style: Style) -> Block: ...
    def padding(
        self, left: int = ..., right: int = ..., top: int = ..., bottom: int = ...
    ) -> Block: ...
    def title_alignment(self, alignment: str) -> Block: ...
    def inner(self, area: Rect) -> Rect: ...

class Paragraph:
    def __init__(self, text: Text) -> None: ...
    @staticmethod
    def from_string(s: str) -> Paragraph: ...
    def block(self, block: Block) -> Paragraph: ...
    def style(self, style: Style) -> Paragraph: ...
    def wrap(self, wrap: bool = ..., trim: bool = ...) -> Paragraph: ...
    def scroll(self, y: int = ..., x: int = ...) -> Paragraph: ...
    def alignment(self, alignment: str) -> Paragraph: ...
    def left_aligned(self) -> Paragraph: ...
    def centered(self) -> Paragraph: ...
    def right_aligned(self) -> Paragraph: ...

class ListItem:
    def __init__(self, text: str, style: Style | None = ...) -> None: ...
    @staticmethod
    def from_text(text: Text) -> ListItem: ...
    def style(self, style: Style) -> ListItem: ...

class ListState:
    def __init__(self) -> None: ...
    @property
    def selected(self) -> int | None: ...
    @property
    def offset(self) -> int: ...
    def select(self, index: int | None = ...) -> None: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...

class ListDirection:
    TopToBottom: ListDirection
    BottomToTop: ListDirection

class List:
    def __init__(self, items: list[ListItem]) -> None: ...
    def block(self, block: Block) -> List: ...
    def style(self, style: Style) -> List: ...
    def highlight_style(self, style: Style) -> List: ...
    def highlight_symbol(self, sym: str) -> List: ...
    def direction(self, dir: ListDirection) -> List: ...
    def repeat_highlight_symbol(self, v: bool) -> List: ...

class Cell:
    def __init__(self, text: str, style: Style | None = ...) -> None: ...
    def style(self, style: Style) -> Cell: ...

class Row:
    def __init__(self, cells: list[Cell]) -> None: ...
    @staticmethod
    def from_strings(texts: list[str]) -> Row: ...
    def style(self, style: Style) -> Row: ...
    def height(self, height: int) -> Row: ...

class TableState:
    def __init__(self) -> None: ...
    @property
    def selected(self) -> int | None: ...
    @property
    def offset(self) -> int: ...
    def select(self, index: int | None = ...) -> None: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...

class Table:
    def __init__(
        self,
        rows: list[Row],
        column_widths: list[Constraint] | None = ...,
        header: Row | None = ...,
        footer: Row | None = ...,
    ) -> None: ...
    def header(self, row: Row) -> Table: ...
    def footer(self, row: Row) -> Table: ...
    def block(self, block: Block) -> Table: ...
    def column_widths(self, widths: list[Constraint]) -> Table: ...
    def style(self, style: Style) -> Table: ...
    def highlight_style(self, style: Style) -> Table: ...
    def highlight_symbol(self, sym: str) -> Table: ...
    def column_spacing(self, n: int) -> Table: ...

class Gauge:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> Gauge: ...
    def percent(self, pct: int) -> Gauge: ...
    def ratio(self, ratio: float) -> Gauge: ...
    def style(self, style: Style) -> Gauge: ...
    def gauge_style(self, style: Style) -> Gauge: ...
    def label(self, label: str) -> Gauge: ...
    def use_unicode(self, v: bool) -> Gauge: ...

class LineGauge:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> LineGauge: ...
    def ratio(self, ratio: float) -> LineGauge: ...
    def percent(self, pct: int) -> LineGauge: ...
    def style(self, style: Style) -> LineGauge: ...
    def gauge_style(self, style: Style) -> LineGauge: ...
    def label(self, label: str) -> LineGauge: ...
    def line_set(self, name: str) -> LineGauge: ...

class Bar:
    def __init__(self, value: int, label: str | None = ...) -> None: ...
    def style(self, style: Style) -> Bar: ...
    def value_style(self, style: Style) -> Bar: ...
    def text_value(self, tv: str) -> Bar: ...

class BarGroup:
    def __init__(self, bars: list[Bar], label: str | None = ...) -> None: ...

class BarChart:
    def __init__(self) -> None: ...
    def data(self, group: BarGroup) -> BarChart: ...
    def block(self, block: Block) -> BarChart: ...
    def bar_width(self, w: int) -> BarChart: ...
    def bar_gap(self, g: int) -> BarChart: ...
    def group_gap(self, g: int) -> BarChart: ...
    def max(self, m: int) -> BarChart: ...
    def style(self, s: Style) -> BarChart: ...
    def bar_style(self, s: Style) -> BarChart: ...
    def value_style(self, s: Style) -> BarChart: ...
    def label_style(self, s: Style) -> BarChart: ...

class Sparkline:
    def __init__(self) -> None: ...
    def data(self, data: list[int]) -> Sparkline: ...
    def block(self, block: Block) -> Sparkline: ...
    def max(self, m: int) -> Sparkline: ...
    def style(self, style: Style) -> Sparkline: ...

class ScrollbarState:
    def __init__(self) -> None: ...
    def content_length(self, n: int) -> ScrollbarState: ...
    def position(self, p: int) -> ScrollbarState: ...
    def scroll_next(self) -> None: ...
    def scroll_prev(self) -> None: ...
    def first(self) -> None: ...
    def last(self) -> None: ...

class ScrollbarOrientation:
    VerticalRight: ScrollbarOrientation
    VerticalLeft: ScrollbarOrientation
    HorizontalBottom: ScrollbarOrientation
    HorizontalTop: ScrollbarOrientation

class Scrollbar:
    def __init__(self, orientation: ScrollbarOrientation | None = ...) -> None: ...
    def orientation(self, o: ScrollbarOrientation) -> Scrollbar: ...
    def thumb_style(self, st: Style) -> Scrollbar: ...
    def track_style(self, st: Style) -> Scrollbar: ...
    def begin_style(self, st: Style) -> Scrollbar: ...
    def end_style(self, st: Style) -> Scrollbar: ...

class Tabs:
    def __init__(self, titles: list[str]) -> None: ...
    def select(self, index: int) -> Tabs: ...
    def block(self, block: Block) -> Tabs: ...
    def style(self, style: Style) -> Tabs: ...
    def highlight_style(self, style: Style) -> Tabs: ...
    def divider(self, d: str) -> Tabs: ...
    def padding(self, left: str, right: str) -> Tabs: ...

class Clear:
    def __init__(self) -> None: ...

class MascotEyeColor:
    Default: MascotEyeColor
    Red: MascotEyeColor

class RatatuiMascot:
    def __init__(self, eye_color: MascotEyeColor | None = ...) -> None: ...
    def set_eye(self, rat_eye: MascotEyeColor) -> RatatuiMascot: ...

class CalendarDate:
    @staticmethod
    def from_ymd(year: int, month: int, day: int) -> CalendarDate: ...
    @staticmethod
    def today() -> CalendarDate: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...

class CalendarEventStore:
    def __init__(self) -> None: ...
    def add(self, date: CalendarDate, style: Style) -> None: ...
    def add_today(self, style: Style) -> None: ...
    @staticmethod
    def today_highlighted(style: Style) -> CalendarEventStore: ...

class Monthly:
    def __init__(self, display_date: CalendarDate, events: CalendarEventStore) -> None: ...
    def block(self, block: Block) -> Monthly: ...
    def default_style(self, style: Style) -> Monthly: ...
    def show_surrounding(self, style: Style) -> Monthly: ...
    def show_month_header(self, style: Style) -> Monthly: ...
    def show_weekdays_header(self, style: Style) -> Monthly: ...

class Canvas:
    def __init__(self, width: int, height: int) -> None: ...
    def draw_line(self, x1: float, y1: float, x2: float, y2: float) -> None: ...
    def draw_point(self, x: float, y: float) -> None: ...
    def draw_rect(self, x: float, y: float, w: float, h: float) -> None: ...
    def clear(self) -> None: ...
    @property
    def len(self) -> int: ...

class MapResolution:
    Low: MapResolution
    High: MapResolution

class Map:
    def __init__(self, resolution: MapResolution | None = ...) -> None: ...
    def resolution(self, resolution: MapResolution) -> Map: ...

class GraphType:
    Scatter: GraphType
    Line: GraphType
    Bar: GraphType

class Marker:
    Dot: Marker
    Block: Marker
    Bar: Marker
    Braille: Marker
    HalfBlock: Marker
    Quadrant: Marker
    Sextant: Marker
    Octant: Marker

class LegendPosition:
    Top: LegendPosition
    TopRight: LegendPosition
    TopLeft: LegendPosition
    Left: LegendPosition
    Right: LegendPosition
    Bottom: LegendPosition
    BottomRight: LegendPosition
    BottomLeft: LegendPosition

class Axis:
    def __init__(self) -> None: ...
    def title(self, title: str) -> Axis: ...
    def bounds(self, min: float, max: float) -> Axis: ...
    def labels(self, labels: list[str]) -> Axis: ...
    def style(self, style: Style) -> Axis: ...
    def labels_alignment(self, alignment: str) -> Axis: ...

class Dataset:
    def __init__(self, data: list[tuple[float, float]]) -> None: ...
    def name(self, name: str) -> Dataset: ...
    def data(self, data: list[tuple[float, float]]) -> Dataset: ...
    def marker(self, marker: Marker) -> Dataset: ...
    def graph_type(self, graph_type: GraphType) -> Dataset: ...
    def style(self, style: Style) -> Dataset: ...

class Chart:
    def __init__(self, datasets: list[Dataset]) -> None: ...
    def add_dataset(self, dataset: Dataset) -> Chart: ...
    def block(self, block: Block) -> Chart: ...
    def datasets(self, datasets: list[Dataset]) -> Chart: ...
    def hidden_legend_constraints(self, width: Constraint, height: Constraint) -> Chart: ...
    def legend_position(self, position: LegendPosition | None = ...) -> Chart: ...
    def style(self, style: Style) -> Chart: ...
    def x_axis(self, axis: Axis) -> Chart: ...
    def y_axis(self, axis: Axis) -> Chart: ...

class PromptStatus:
    Pending: PromptStatus
    Complete: PromptStatus
    Aborted: PromptStatus

class TextRenderStyle:
    Normal: TextRenderStyle
    Password: TextRenderStyle
    Invisible: TextRenderStyle

class TextState:
    def __init__(self, initial: str = ...) -> None: ...
    def focus(self) -> None: ...
    def blur(self) -> None: ...
    @property
    def is_focused(self) -> bool: ...
    def value(self) -> str: ...
    def set_value(self, v: str) -> None: ...
    def clear_input(self) -> None: ...
    @property
    def cursor_pos(self) -> int: ...
    @property
    def status(self) -> PromptStatus: ...
    def is_pending(self) -> bool: ...
    def is_complete(self) -> bool: ...
    def is_aborted(self) -> bool: ...
    def reset_status(self) -> None: ...
    def reset(self) -> None: ...
    def handle_key(self, ev: object) -> bool: ...

class TextPrompt:
    def __init__(self, label: str, render_style: TextRenderStyle | None = ...) -> None: ...
    def with_render_style(self, style: TextRenderStyle) -> TextPrompt: ...

class PasswordPrompt:
    def __init__(self, label: str) -> None: ...

def prompt_text(label: str) -> str | None: ...
def prompt_password(label: str) -> str | None: ...

class KeyEvent:
    @property
    def code(self) -> str: ...
    @property
    def ctrl(self) -> bool: ...
    @property
    def alt(self) -> bool: ...
    @property
    def shift(self) -> bool: ...

class Frame:
    @property
    def area(self) -> Rect: ...
    def render_widget(self, widget: object, area: Rect) -> None: ...
    def render_stateful_list(self, widget: List, area: Rect, state: ListState) -> None: ...
    def render_stateful_table(self, widget: Table, area: Rect, state: TableState) -> None: ...
    def render_stateful_scrollbar(
        self, widget: Scrollbar, area: Rect, state: ScrollbarState
    ) -> None: ...
    def render_text_prompt(self, prompt: TextPrompt, area: Rect, state: TextState) -> None: ...
    def render_password_prompt(
        self, prompt: PasswordPrompt, area: Rect, state: TextState
    ) -> None: ...

class Terminal:
    def __init__(self, inline_height: int | None = ...) -> None: ...
    def __enter__(self) -> Terminal: ...
    def __exit__(self, *args: object) -> bool: ...
    def restore(self) -> None: ...
    def draw(self, draw_fn: Callable[[Frame], None]) -> None: ...
    def poll_event(self, timeout_ms: int = ...) -> KeyEvent | None: ...
    def area(self) -> Rect: ...
    def clear(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...
